global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'strictdoc-service'
    static_configs:
      - targets: ['strictdoc-service:9183']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
